### ISSUE TITLE
Is it possible to export the Sample1344.PmuCapture as a csv file

### ISSUE THREAD

**Issue by Time4Summer** [GridProtectionAlliance/PMUConnectionTester#10]
Hello,

Is it possible to export the Sample1344.PmuCapture as a csv file?

**Comment by StephenCWills** [comment]
Yes, use `File > Capture > Start Stream Debug Capture...`

**Comment by Time4Summer** [comment]
That does export the data as a csv, but  there are no column headers....

**Comment by StephenCWills** [comment]
Seems like it will put out a header when it receives the config frame. In my testing, when I started the debug capture before "connecting" to the sample file, it placed the header on line 3.

**Comment by Time4Summer** [comment]
Ok that worked.
