### ISSUE TITLE
Is it possible to play the Sample1344.PmuCapture thru the local host rather then the file option

### ISSUE THREAD

**Issue by Time4Summer** [GridProtectionAlliance/PMUConnectionTester#11]
I would like to run the  Sample1344.PmuCapture through the local host rather then using the  file Option, is this possible?

**Comment by StephenCWills** [comment]
You can replay capture files in openPDC (https://github.com/GridProtectionAlliance/openPDC). Or, if you're good at writing C# applications, you can start with the following tutorial and adapt it for your needs.
https://github.com/GridProtectionAlliance/openPDC/blob/master/Source/Documentation/wiki/Developers_Device_to_Data_in_5_Easy_Steps.md
