### ISSUE TITLE
IEEE1344-1995 UDP Multicast not working in 4.5.11 whereas it is working in 4.4.0 version 

### ISSUE THREAD

**Issue by ssen6547** [GridProtectionAlliance/PMUConnectionTester#7]
IEEE1344-1995 UDP Multicast not working in 4.5.11 whereas it is working in 4.4.0 version. It Show Exception : Data channels user unhandled expection : Only one usuage of each socket address (protocol/network address/port) is normally permitted. And when we enable real-time data, we get Exception : Index was outside the bounds of the array.

**Comment by ritchiecarroll** [comment]
The most likely cause of this exception is that another program is running with this port in use. You can run `netstat -b` from an administrative command prompt to see which application has the port open.

**Comment by ritchiecarroll** [comment]
This still an issue?

**Comment by ritchiecarroll** [comment]
Going to go ahead close this due lack of activity - please feel free to re-open if you think it is still an issue.  Thanks!
